### ISSUE TITLE
abilities of the module

### ISSUE THREAD

**Issue by danilsmakotin** [mway-io/titanium-barcode#1]
Hello, guys! I have 2 questions about this beautiful module.
1. What kinds of barcodes i can scan with your module? i want scan QR-code, it's possible?
2. Can i use overlay views as imageView on scan screen?

**Comment by pfleidi** [comment]
Hello,
1. We currently support: UPC_A, UPC_E, EAN_13, EAN_8, CODE_39, CODE_128, ITF, QR_CODE, DATA_MATRIX. More formats could be added since the ZXing library supports a LOT of them.
2. We currently don't support overlay views. The scanner is itself an activity for itself.
